# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: anvudh@gmail.com
author_name: An Vu
cloud_provider: vercel
preset_name: production
project_name: algo-dapp-frontend

